name: Terraform CI - Validate & Lint on Every Commit

on:
  push:
    branches:
      - "**"       
  # pull_request:
  #   branches:
  #     - "**"      



jobs:
  terraform-validate:
    name: Terraform Validate & Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev]

    defaults:
      run:
        working-directory: env/${{ matrix.env }}

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: ğŸ”§ Terraform Init (skip backend for validation)
        run: terraform init -backend=false

      - name: âœ… Terraform Validate
        run: terraform validate

      - name: ğŸ“ Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.53.0

      - name: ğŸ§¹ Run TFLint
        run: |
          tflint --init
          tflint

  terraform-security:
    name: Terraform Security Scan (tfsec)
    runs-on: ubuntu-latest
    needs: terraform-validate

    strategy:
      matrix:
        env: [dev]

    defaults:
      run:
        working-directory: env/${{ matrix.env }}

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”’ Run tfsec (IaC security scan)
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working-directory: envs/${{ matrix.env }}
          additional_args: --soft-fail
